### ISSUE TITLE
【ModuleNotFoundError: No module named 'src'】运行app.py报错

### ISSUE THREAD

**Issue by LouisHeck** [KevinWang676/ChatGLM2-Voice-Cloning#2]
运行 app.py
root@autodl-container-71644691e8-64a9194f:~/FreeVC# python app.py 

报错如下：
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from src.gradio_demo import SadTalker  
ModuleNotFoundError: No module named 'src'

![1689831028592](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/38588261/8c8900fd-0ca7-4292-b8f2-ad556d4ebcf6)

**Comment by KevinWang676** [comment]
感谢提问，如果想使用SadTalker，需要运行`git clone https://huggingface.co/spaces/kevinwang676/ChatGLM2-SadTalker.git`，参考v2的教程；`No module named 'src'`可能是因为没有执行`cd ChatGLM2-SadTalker`

**Comment by LouisHeck** [comment]
> 感谢提问，如果想使用SadTalker，需要运行`git clone https://huggingface.co/spaces/kevinwang676/ChatGLM2-SadTalker.git`，参考v2的教程；`No module named 'src'`可能是因为没有执行`cd ChatGLM2-SadTalker`

再问一下，v2的教程在哪里

**Comment by KevinWang676** [comment]
就在这个项目里

![image](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/126712357/3f4790d5-a947-4ebf-938f-0aa548be4e0f)
