### ISSUE TITLE
点击 “开始AI克隆声音吧” 报这个错误：

### ISSUE THREAD

**Issue by ZenXir** [KevinWang676/ChatGLM2-Voice-Cloning#7]
![image](https://github.com/KevinWang676/ChatGLM2-Voice-Cloning/assets/57025873/0e14b1eb-22ba-45e6-8e7d-851b9f3e31f3)

**Comment by ZenXir** [comment]
在页面直接点击上传音频就可以  不用把音频放在特定目录下是吧？
看提示是音频文件没找到

**Comment by lzy83925** [comment]
我也出现了这个错，看提示貌似是不支持mp3，如果是这样，请作者把上传文件这里给个提示或限制只能上传wav

`DEBUG:pydub.converter:subprocess.call(['ffmpeg', '-y', '-i', '/tmp/gradio/f2c4231a9adf732ba5ec4f89da2204e1a3418336/梁朝伟声音.MP3', '-acodec', 'pcm_s16le', '-vn', '-f', 'wav', '-'])
Traceback (most recent call last):
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/root/workspace/ChatGLM2-SadTalker/app.py", line 93, in convert
    wav_src, _ = librosa.load(src, sr=hps.data.sampling_rate)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/core/audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/core/audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/soundfile.py", line 1212, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: None
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Tue, 25 Jul 2023 03:45:49 GMT'), (b'server', b'uvicorn'), (b'content-length', b'30'), (b'content-type', b'application/json')])
INFO:httpx:HTTP Request: POST http://localhost:7861/api/predict "HTTP/1.1 500 Internal Server Error"`

**Comment by lzy83925** [comment]
> 我也出现了这个错，看提示貌似是不支持mp3，如果是这样，请作者把上传文件这里给个提示或限制只能上传wav
> 
> `DEBUG:pydub.converter:subprocess.call(['ffmpeg', '-y', '-i', '/tmp/gradio/f2c4231a9adf732ba5ec4f89da2204e1a3418336/梁朝伟声音.MP3', '-acodec', 'pcm_s16le', '-vn', '-f', 'wav', '-']) Traceback (most recent call last): File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict output = await app.get_blocks().process_api( File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api result = await self.call_function( File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/blocks.py", line 1094, in call_function prediction = await anyio.to_thread.run_sync( File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/gradio/utils.py", line 703, in wrapper response = f(*args, **kwargs) File "/root/workspace/ChatGLM2-SadTalker/app.py", line 93, in convert wav_src, _ = librosa.load(src, sr=hps.data.sampling_rate) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/util/decorators.py", line 88, in inner_f return f(*args, **kwargs) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/core/audio.py", line 164, in load y, sr_native = __soundfile_load(path, offset, duration, dtype) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/librosa/core/audio.py", line 195, in __soundfile_load context = sf.SoundFile(path) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/soundfile.py", line 658, in __init__ self._file = self._open(file, mode_int, closefd) File "/root/anaconda3/envs/glmsd1/lib/python3.10/site-packages/soundfile.py", line 1212, in _open raise TypeError("Invalid file: {0!r}".format(self.name)) TypeError: Invalid file: None DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Tue, 25 Jul 2023 03:45:49 GMT'), (b'server', b'uvicorn'), (b'content-length', b'30'), (b'content-type', b'application/json')]) INFO:httpx:HTTP Request: POST http://localhost:7861/api/predict "HTTP/1.1 500 Internal Server Error"`

然而然并卵，我上传了wav文件，还是报错。。。。

**Comment by ZenXir** [comment]
是的 wav报一样错误  等待作者大佬消息

**Comment by coressss** [comment]
裁剪音频时长到5s以内即可

**Comment by ZenXir** [comment]
@coressss 我尝试了好几次 裁剪的音频5s以内 还是报一样的错误
你的pip list 环境可以分享下吗？

**Comment by lzy83925** [comment]
@ZenXir 我的可以分享给你，我的只要是wav就行，上传了个2分钟多的音频也没问题，但是不稳定，有时候好，有时候报错。
Package                   Version
------------------------- ---------------
absl-py                   1.4.0
accelerate                0.21.0
addict                    2.4.0
aiofiles                  23.1.0
aiohttp                   3.8.5
aiosignal                 1.3.1
altair                    5.0.1
annotated-types           0.5.0
anyio                     3.7.1
async-timeout             4.0.2
attrs                     23.1.0
audioread                 3.0.0
av                        10.0.0
basicsr                   1.4.2
cachetools                5.3.1
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.6
cmake                     3.27.0
contourpy                 1.1.0
cpm-kernels               1.0.11
cycler                    0.11.0
decorator                 5.1.1
edge-tts                  6.1.7
exceptiongroup            1.1.2
face-alignment            1.3.5
facexlib                  0.3.0
fastapi                   0.100.0
ffmpy                     0.3.1
filelock                  3.12.2
filterpy                  1.4.5
fonttools                 4.41.1
frozenlist                1.4.0
fsspec                    2023.6.0
future                    0.18.3
gfpgan                    1.3.8
google-auth               2.22.0
google-auth-oauthlib      1.0.0
gradio                    3.38.0
gradio_client             0.2.10
grpcio                    1.56.2
h11                       0.14.0
httpcore                  0.17.3
httpx                     0.24.1
huggingface-hub           0.16.4
idna                      3.4
imageio                   2.19.3
imageio-ffmpeg            0.4.7
importlib-metadata        6.8.0
Jinja2                    3.1.2
joblib                    1.1.0
jsonschema                4.18.4
jsonschema-specifications 2023.7.1
kiwisolver                1.4.4
kornia                    0.6.8
latex2mathml              3.76.0
librosa                   0.9.2
linkify-it-py             2.0.2
lit                       16.0.6
llvmlite                  0.40.1
lmdb                      1.4.1
loguru                    0.7.0
Markdown                  3.4.3
markdown-it-py            2.2.0
MarkupSafe                2.1.3
matplotlib                3.7.2
mdit-py-plugins           0.3.3
mdtex2html                1.2.0
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.4
networkx                  3.1
numba                     0.57.1
numpy                     1.23.4
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
oauthlib                  3.2.2
opencv-python             4.8.0.74
orjson                    3.9.2
packaging                 23.1
pandas                    2.0.3
Pillow                    10.0.0
pip                       23.1.2
platformdirs              3.9.1
pooch                     1.7.0
protobuf                  4.23.4
psutil                    5.9.5
pyasn1                    0.5.0
pyasn1-modules            0.3.0
pycparser                 2.21
pydantic                  2.0.3
pydantic_core             2.3.0
pydub                     0.25.1
pyparsing                 3.0.9
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3
PyWavelets                1.4.1
PyYAML                    6.0.1
referencing               0.30.0
regex                     2023.6.3
requests                  2.31.0
requests-oauthlib         1.3.1
resampy                   0.3.1
rpds-py                   0.9.2
rsa                       4.9
safetensors               0.3.1
scikit-image              0.19.3
scikit-learn              1.1.3
scipy                     1.10.1
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                67.8.0
six                       1.16.0
sniffio                   1.3.0
soundfile                 0.12.1
starlette                 0.27.0
sympy                     1.12
tb-nightly                2.14.0a20230724
tensorboard-data-server   0.7.1
threadpoolctl             3.2.0
tifffile                  2023.7.18
tokenizers                0.13.3
tomli                     2.0.1
toolz                     0.12.0
torch                     2.0.1
torchvision               0.15.2
tqdm                      4.65.0
transformers              4.31.0
triton                    2.0.0
typing_extensions         4.7.1
tzdata                    2023.3
uc-micro-py               1.0.2
urllib3                   1.26.16
uvicorn                   0.23.1
webrtcvad                 2.0.10
websockets                11.0.3
Werkzeug                  2.3.6
wheel                     0.38.4
yacs                      0.1.8
yapf                      0.40.1
yarl                      1.9.2
zipp                      3.16.2

**Comment by ZenXir** [comment]
@coressss 好嘞 我安装成一样的试试

**Comment by ZenXir** [comment]
@coressss @KevinWang676 还是报一样的错误
是不是远程访问的原因？

我是：
在一台GPU较好的A机器上跑服务，服务设置成 server_name="0.0.0.0", server_port=6006
用一个不太吵的B机器，在浏览器上访问服务，拖放的音频是B机器上的音频

是不是A机器通过路径查找的音频文件，并没有将B机器上的音频上传到A机器？

**Comment by ZenXir** [comment]
@KevinWang676 @coressss @lzy83925 大家好 问题解决了 刚调试了下，发现是“克隆音频时src为none”
原来是，得先生成音频，再克隆音频，【不可以直接克隆音频，否则conver和的src为none】
感谢作者大佬分享 期待大佬分享更多训练和学习资料
